spring.application.name=Bank
spring.datasource.url=jdbc:mysql://localhost:3306/bank_db
spring.datasource.username=root
spring.datasource.password=Data@1234_

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080